version: '3.6'
services:
  node:
    build:
      context: .
      args:
        - NODE_ENV=development
    command: ../node_modules/.bin/nodemon -L --inspect=0.0.0.0:9229 ./bin/www
    env_file: .env
    ports:
      - "3000:3000"
      - "9229:9229"
      - "9230:9230"
    volumes:
      - .:/opt/node_app/app
      - ./package.json:/opt/node_app/package.json
      - ./package-lock.json:/opt/node_app/package-lock.json
      - notused:/opt/node_app/app/node_modules
volumes:
  notused:
